name: Docker Image CI

on:
  push:
    branches: [ "acme-branch" ]
  pull_request:
    branches: [ "acme-branch" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
